name: Sync to Backup

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to backup
        env:
          BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git remote add backup https://gotime-transportation:${BACKUP_TOKEN}@github.com/gotime-transportation/gotime.git
          git push backup main --force
